# Generated by Django 4.1.3 on 2022-12-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_regularuser_age_regularuser_preference'),
        ('user_functionality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_functionality.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.regularuser')),
            ],
        ),
    ]
